<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-10-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=200),
        ),
    ]
=======
# Generated by Django 2.2.5 on 2019-10-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='', max_length=200),
        ),
    ]
>>>>>>> 0f2e3bf08cb23908bad5d4911f58b073ee1a305b
